# Generated by Django 4.2.29 on 2026-06-24 02:00

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_cliente_saldo_a_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deuda_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deuda previa del cliente antes de usar el sistema. Se convierte en CxC al guardar.', max_digits=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='almacen_inicial',
            field=models.ForeignKey(blank=True, help_text='Almacén donde se depositará el stock inicial. Si no se selecciona, se usará el primer almacén activo.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='nucleo.almacen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 24, 2, 0, 41, 479125, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock con el que inicia este producto en el sistema.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.venta'),
        ),
    ]
