# Generated by Django 4.2.29 on 2026-07-23 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_cliente_deuda_inicial_producto_almacen_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='tasa_actualizada_el',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última actualización de la tasa', null=True),
        ),
        migrations.CreateModel(
            name='BorradorFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_json', models.JSONField()),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('total_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_secundaria', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.cliente')),
            ],
            options={
                'verbose_name': 'Borrador de Factura',
                'verbose_name_plural': 'Borradores de Facturas',
                'ordering': ['-creado_el'],
            },
        ),
    ]
