# Generated by Django 4.2.29 on 2026-07-27 10:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_alter_borradorfactura_cajero'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=15)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_venta_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_venta_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_efectivo_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_pago_movil_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_punto_venta_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_cobranzas_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_creditos_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_gastos_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('recaudado_esperado_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('recaudado_real_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('diferencia_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('observacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.almacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta de Mercado',
                'verbose_name_plural': 'Rutas de Mercado',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RutaMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_usd_equivalente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.metodopago')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='nucleo.rutamercado')),
            ],
            options={
                'verbose_name': 'Pago de Ruta',
                'verbose_name_plural': 'Pagos de Ruta',
            },
        ),
        migrations.CreateModel(
            name='RutaMercadoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.conceptoegreso')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='nucleo.rutamercado')),
            ],
            options={
                'verbose_name': 'Gasto de Ruta',
                'verbose_name_plural': 'Gastos de Ruta',
            },
        ),
        migrations.CreateModel(
            name='RutaMercadoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cantidad_entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('precio_venta_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.presentacionproducto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nucleo.rutamercado')),
            ],
            options={
                'verbose_name': 'Detalle de Ruta',
                'verbose_name_plural': 'Detalles de Ruta',
            },
        ),
        migrations.CreateModel(
            name='RutaMercadoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.cliente')),
                ('cuenta_cobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_ruta', to='nucleo.cuentaporcobrar')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='nucleo.rutamercado')),
            ],
            options={
                'verbose_name': 'Crédito de Ruta',
                'verbose_name_plural': 'Créditos de Ruta',
            },
        ),
    ]
