# Generated by Django 4.2.16 on 2026-03-01 20:14

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('CAJERO', 'Cajero')], default='CAJERO', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(help_text='RIF, Cédula, NIT, etc.', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROCESADA', 'Procesada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('tasa_cambio_historica', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_impuestos_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_secundaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('almacen', models.ForeignKey(help_text='Almacén de origen o destino', on_delete=django.db.models.deletion.RESTRICT, to='nucleo.almacen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_principal', models.CharField(default='USD', help_text='Ej. USD', max_length=10)),
                ('moneda_secundaria', models.CharField(default='BS', help_text='Ej. BS', max_length=10)),
                ('tasa_cambio_actual', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=15)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.compra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. IVA, Exento', max_length=50, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ej. 16.00', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(help_text='RIF, Cédula, NIT, etc.', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=15)),
                ('fondo_inicial_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fondo_inicial_secundaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reporte_cierre_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reporte_cierre_secundaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('usuario', models.ForeignKey(help_text='Cajero responsable', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sesiones de Caja',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Kilogramo, Unidad', max_length=50, unique=True)),
                ('sigla', models.CharField(help_text='Ej. kg, und', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROCESADA', 'Procesada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('tasa_cambio_historica', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_impuestos_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_secundaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('almacen', models.ForeignKey(help_text='Almacén de origen o destino', on_delete=django.db.models.deletion.RESTRICT, to='nucleo.almacen')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.cliente')),
                ('sesion_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='nucleo.sesioncaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_base', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('costo_base_moneda_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.categoria')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.impuesto')),
                ('unidad_medida', models.ForeignKey(help_text='Unidad mínima de control', on_delete=django.db.models.deletion.RESTRICT, to='nucleo.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Bulto x 24', max_length=100)),
                ('factor_conversion', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad de unidades base que contiene', max_digits=15)),
                ('precio_venta_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio manual en moneda principal', max_digits=15)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='nucleo.producto')),
            ],
            options={
                'verbose_name_plural': 'Presentaciones de Productos',
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_abono_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_entregado_secundaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tasa_cambio_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('referencia', models.CharField(blank=True, help_text='Ej. Efectivo, Zelle, Transferencia #123', max_length=100)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='nucleo.cuentaporpagar')),
                ('usuario', models.ForeignKey(help_text='Usuario que emitió el pago', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_abono_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_entregado_secundaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tasa_cambio_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('referencia', models.CharField(blank=True, help_text='Ej. Efectivo, Zelle, Transferencia #123', max_length=100)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='nucleo.cuentaporcobrar')),
                ('usuario', models.ForeignKey(help_text='Cajero que recibió el pago', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_presentacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_impuesto_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.presentacionproducto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nucleo.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_presentacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_impuesto_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nucleo.compra')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.presentacionproducto')),
            ],
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.proveedor'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.venta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InventarioAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual_unidades_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_por_almacen', to='nucleo.producto')),
            ],
            options={
                'verbose_name_plural': 'Inventarios en Almacenes',
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
