# Generated by Django 4.2.29 on 2026-05-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_remove_presentacionproducto_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Efectivo USD, Pago Móvil, Zelle', max_length=50, unique=True)),
                ('moneda_referencia', models.CharField(choices=[('PRINCIPAL', 'Moneda Principal (USD)'), ('SECUNDARIA', 'Moneda Secundaria (BS)')], default='PRINCIPAL', max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Lo que entregó el cliente en la moneda del método', max_digits=15)),
                ('monto_equivalente_principal', models.DecimalField(decimal_places=2, help_text='Equivalencia en USD para cuadrar', max_digits=15)),
                ('tasa_cambio_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.metodopago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='nucleo.venta')),
            ],
        ),
    ]
