# Generated by Django 4.2.29 on 2026-06-20 00:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_configuracionglobal_cajero_puede_cambiar_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo positivo acumulado por abonos superiores a la deuda. Se aplica automáticamente en próximas compras a crédito.', max_digits=15),
        ),
    ]
