# Generated by Django 4.2.29 on 2026-05-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_metodopago_pagoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='permitir_stock_negativo',
            field=models.BooleanField(default=False, help_text='Permite vender sin stock disponible'),
        ),
    ]
