# Generated by Django 4.2.29 on 2026-05-13 10:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_configuracionglobal_permitir_stock_negativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('OPERATIVO', 'Gasto Operativo (Servicios, Limpieza, etc)'), ('NOMINA', 'Pago de Nómina / Adelantos'), ('INTERNO', 'Consumo Interno (Uso del negocio)'), ('DONACION', 'Donación / Cortesía'), ('OTRO', 'Otro tipo de salida')], default='OPERATIVO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de Egreso',
                'verbose_name_plural': 'Conceptos de Egresos',
            },
        ),
        migrations.CreateModel(
            name='EgresoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=15)),
                ('total_costo_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('observacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.almacen')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.conceptoegreso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso de Inventario',
                'verbose_name_plural': 'Egresos de Inventario',
            },
        ),
        migrations.CreateModel(
            name='EgresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_extraido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda_extraida', models.CharField(choices=[('PRINCIPAL', 'USD'), ('SECUNDARIA', 'BS')], max_length=15)),
                ('monto_equivalente_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_cambio_momento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacion', models.TextField(blank=True, help_text='Ej: Pago de botellón de agua')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.conceptoegreso')),
                ('sesion_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_efectivo', to='nucleo.sesioncaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEgresoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_unitario_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_costo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nucleo.egresoinventario')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.presentacionproducto')),
            ],
        ),
    ]
