# Generated by Django 4.2.29 on 2026-05-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_conceptoegreso_egresoinventario_egresocaja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='cajero_puede_cambiar_precio',
            field=models.BooleanField(default=False, help_text="Permite a los usuarios con rol 'Cajero' modificar el precio de los productos en el POS"),
        ),
    ]
