# Generated by Django 4.2.29 on 2026-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_configuracionglobal_tasa_actualizada_el_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borradorfactura',
            name='carrito_json',
            field=models.JSONField(default=list),
        ),
    ]
