# Generated by Django 4.2.29 on 2026-07-23 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_alter_borradorfactura_carrito_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borradorfactura',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
