"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8%!$#ua2h6)3w1ioaz^(slvk%b)7$(sp#_wpm&%e9q!th-bmn('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [*]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- LIBRERÍAS NUEVAS QUE INSTALAMOS ---
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # --- NUESTRA APLICACIÓN ---
    'nucleo',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Debe estar lo más arriba posible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Usamos el motor de MySQL para MariaDB
        'NAME': 'erp_bimonetario',            # El nombre exacto que creaste en phpMyAdmin
        'USER': 'root',                       # Usuario por defecto de XAMPP
        'PASSWORD': '',                       # XAMPP no tiene contraseña por defecto
        'HOST': 'localhost',                  # Tu propia computadora
        'PORT': '3306',                       # El puerto por defecto de MariaDB
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


AUTH_USER_MODEL = 'nucleo.Usuario'


# =============================================================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK (DRF)
# =============================================================================
REST_FRAMEWORK = {
    # Define cómo DRF maneja la autenticación.
    # Le decimos que el método por defecto y principal es JWTAuthentication.
    # Cuando una petición llega, DRF usará esta clase para intentar decodificar
    # el token 'Bearer' y encontrar al usuario asociado.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Define los permisos por defecto para todas las vistas.
    # 'IsAuthenticated' significa que, por defecto, ninguna vista podrá ser
    # accedida por usuarios anónimos, a menos que se anule explícitamente.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# =============================================================================
# CONFIGURACIÓN DE CORS (Cross-Origin Resource Sharing)
# =============================================================================
# Permitimos que cualquier dominio (origen) nos haga peticiones.
# En un entorno de producción, es MUY RECOMENDABLE cambiar esto a la URL
# específica donde vive tu frontend. Ejemplo:
# CORS_ALLOWED_ORIGINS = [
#     "http://mi-dominio-frontend.com",
# ]
CORS_ALLOW_ALL_ORIGINS = True

# --- LA SOLUCIÓN AL ERROR "403 CREDENTIALS NOT PROVIDED" ---
# El navegador, por seguridad, no envía cabeceras "peligrosas" como 'Authorization'
# a menos que el servidor se lo permita explícitamente.
# Esta lista blanca le dice al navegador: "Confío en ti, puedes enviarme
# la cabecera 'Authorization', la estoy esperando".
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  # <-- La cabecera clave que faltaba
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Define el tipo de clave primaria por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
